version: "3.9"
services:
  queuepilot:
    build: .
    container_name: queuepilot
    restart: unless-stopped
    networks:
      - vlan10_net
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./logs:/app/logs

volumes:
  db_data:

networks:
  vlan10_net:
    external: true
    name: vlan10_net