version: "3.9"
services:
  queuepilot:
    build: .
    container_name: queuepilot
    restart: unless-stopped
    # Change network to match your setup
    networks:
      - vlan20_net
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./logs:/app/logs

volumes:
  db_data:

# This might not be needed if you have your own network setup
networks:
  vlan10_net:
    external: true
    name: vlan20_net
